jobs: 2
log_path: /tmp/ovn_ci
image_name: ghcr.io/ovn-org/ovn-tests:fedora
host: localhost

git:
  ovn_path: /tmp/ovn
  ovs_path: /tmp/ovn/ovs
  update: false

suites:
  - name: Compile
    compiler: gcc
    options: --disable-ssl

  - name: Tests
    compiler: gcc
    type: unit
    test_range: 1

  - name: Tests
    compiler: clang
    type: unit
    sanitizers: true
    test_range: 1
